gitとGitHubについての記事
Zli-UoA/zli_blog pull request #26
Opened 2023-06-10 12:38 UTC by yuorei

git GitHubについて書きました。一旦の完成です。
まだ追加するかもしれないです。

2023-06-20 15:33 UTC, Kai-Z-JP commented on public/articles/git_github/index.md
> +今回はgit,GitHubについて解説していきます。この記事を読めばgit,GitHubを最低限は使えるようになると思います。ぜひ参考にしてみてください。
```suggestion
今回はgit,GitHubについて解説していきます。この記事を読めばgit, GitHubを最低限は使えるようになると思います。ぜひ参考にしてみてください。  
```

2023-06-20 15:36 UTC, Kai-Z-JP commented on public/articles/git_github/index.md
> +これでバージョンが出てきていればすでにダウンロード済みなのでここは飛ばしてください。
`ここは飛ばしてください。`の`ここ`が指し示すことが不明瞭

2023-06-20 15:37 UTC, Kai-Z-JP commented on public/articles/git_github/index.md
> +ダウンロードが終わったら先ほどのコマンドを実行してバージョンが出たらダウンロード完了です。
ダウンロードしただけでインストールはされません。

2023-06-20 15:38 UTC, Kai-Z-JP commented on public/articles/git_github/index.md
> +git config --global user.email "example@example.com"
適宜変更してくださいなら`user.name`もexampleで良いのでは

2023-06-20 15:40 UTC, Kai-Z-JP commented on public/articles/git_github/index.md
> +`git init`を使うことで作成ができます。もしもともと存在していた場合は再度作り直されます。`.git`のあるディレクトリで作業をします。
```suggestion
`git init`を使うことで作成ができます。もし、リポジトリがもともと存在していた場合は再度作り直されます。`.git`のあるディレクトリで作業をします。
```

2023-06-20 15:40 UTC, Kai-Z-JP commented on public/articles/git_github/index.md
> +`.git`があるかを確認するには`ls -a`で確認してみてください。これがGitリポジトリです。現在は空にGitリポジトリです。
文章の意味がわかりません。

2023-06-20 15:42 UTC, Kai-Z-JP commented on public/articles/git_github/index.md
> +共同作業をするときは、branchをきって作業できるのでmainのbranchには影響をあたえずに作業できます。
HEAD...?

2025-03-23 10:22 UTC, kashu-02 requested changes
途中で読むのがつかれてきた
とりあえずここまで

2025-03-23 10:22 UTC, kashu-02 commented on public/articles/git_github/index.md
> +今回はgit, GitHubについて解説していきます。この記事を読めばgit, GitHubを最低限は使えるようになると思います。ぜひ参考にしてみてください。
gitはGitでは(大文字)

2025-03-23 10:22 UTC, kashu-02 commented on public/articles/git_github/index.md
> +ここからダウンロードしてください。
パッケージマネージャー経由でいれないのはびみょい気がする

2025-03-23 10:22 UTC, kashu-02 commented on public/articles/git_github/index.md
> +`--global`とはグローバルに設定をするという意味があります。つまり今後gitを使う時のデフォルトが、全て今設定したものとなります。`--global` を省略すると、現在のリポジトリ内（ローカル）にのみ設定が適用されます。
リポジトリの説明を加えたほうがいい

2025-03-23 10:24 UTC, yuorei commented on public/articles/git_github/index.md
> +今回はgit, GitHubについて解説していきます。この記事を読めばgit, GitHubを最低限は使えるようになると思います。ぜひ参考にしてみてください。
よく見たら公式ページのタイトルGitだったので直します

2025-03-23 10:47 UTC, yuorei commented on public/articles/git_github/index.md
> +ここからダウンロードしてください。
パッケージマネージャー経由でいれているサイトにリンクを変えた

https://github.com/git-guides/install-git

2025-03-31 03:36 UTC, 39sho commented
デザイン崩れてるがなんでだろ

2025-04-17 09:40 UTC, kashu-02 requested changes
LBTM

2025-05-11 08:19 UTC, merged