aizuhack2023ブログ
Zli-UoA/zli_blog pull request #27
Opened 2023-09-20 07:33 UTC by yuorei

aizuhack2023についての記事を書きました。

2023-09-20 10:02 UTC, kashu-02 requested changes
もう一度文章を読み直し、誤字脱字の修正と推敲をしてください。

2023-09-20 10:11 UTC, kashu-02 requested changes

2023-09-20 10:11 UTC, kashu-02 commented on public/articles/aizuhack-2023/index.md
> +勉強会では、各コースの講師とメンターが教えます。参加者のほかんどが1,2年生で、プログラミング初心者です。
> 勉強会では、各コースの講師とメンターが教えます。

何を？？

参加者の**ほかんど**が

2023-09-20 10:11 UTC, kashu-02 commented on public/articles/aizuhack-2023/index.md
> +1ヶ月間チームメンバーと協力して、アイデアソンで出たアイデアを実現するために、プログラミングを行いました。各自で調べたりメンターに相談するなどしてハッカソン中に新しい技術を取得するチームもいました。最終的には、各チームが素晴らしいもの制作できました。
新しい技術を**取得**→新しい技術を**習得**

2023-09-20 10:11 UTC, kashu-02 commented on public/articles/aizuhack-2023/index.md
> +受賞チームにその場で賞品の受け渡して受賞チームメンバーから一言ずつコメントを貰いました。
受け渡し**を**して

2023-09-20 10:11 UTC, kashu-02 commented on public/articles/aizuhack-2023/index.md
> +## 勉強会
下の「勉強会」の見出しとduplicate？

2023-09-28 07:12 UTC, kashu-02 approved these changes
いいだろう。

2023-09-28 12:18 UTC, Kai-Z-JP requested changes
ダメです

2023-09-29 05:22 UTC, yuorei commented
@Kai-Z-JP 直したぞ!

2023-09-29 19:40 UTC, Kai-Z-JP approved these changes

2023-09-30 12:07 UTC, merged